#!/bin/bash

# 本地測試 GitHub Actions workflow 的關鍵邏輯
# 文件：test-workflow-locally.sh

set -e  # 遇到錯誤立即退出

echo "🧪 開始本地測試 GitHub Actions workflow..."
echo ""

# ==================================================
# Step 1: 檢測環境
# ==================================================
echo "📋 Step 1: 檢查環境..."

if ! command -v node &> /dev/null; then
    echo "❌ Node.js 未安裝"
    exit 1
fi

if ! command -v git &> /dev/null; then
    echo "❌ Git 未安裝"
    exit 1
fi

echo "✅ Node.js 版本: $(node --version)"
echo "✅ npm 版本: $(npm --version)"
echo "✅ Git 版本: $(git --version)"
echo ""

# ==================================================
# Step 2: 檢查是否在 git repository 中
# ==================================================
echo "📋 Step 2: 檢查 Git repository..."

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ 不在 Git repository 中"
    exit 1
fi

echo "✅ 當前分支: $(git branch --show-current)"
echo ""

# ==================================================
# Step 3: 模擬檢測變更的文件
# ==================================================
echo "📋 Step 3: 檢測模板文件變更..."

# 模擬 workflow 中的變更檢測邏輯
CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -E "src/data/(styles/templates|components)/.*\.(js|jsx)$" || echo "")

if [ -z "$CHANGED_FILES" ]; then
    echo "ℹ️  沒有檢測到模板文件變更"
    echo "提示：您可以手動修改一個模板文件來測試完整流程"
else
    echo "✅ 檢測到變更的文件："
    echo "$CHANGED_FILES"
fi
echo ""

# ==================================================
# Step 4: 測試 Heredoc commit 訊息語法
# ==================================================
echo "📋 Step 4: 測試 Heredoc commit 訊息語法..."

# 測試 Heredoc 語法（不實際執行 git commit）
TEST_COMMIT_MSG=$(cat <<EOF
chore: update template metadata [skip ci]

Automated metadata update triggered by template changes.

Changes detected in:
$(git diff --cached --name-only --diff-filter=M 2>/dev/null | head -5 || echo "No staged changes")

This commit is automatically generated by the track-template-updates workflow.
EOF
)

echo "✅ Heredoc 語法測試成功！"
echo ""
echo "生成的 commit 訊息預覽："
echo "----------------------------------------"
echo "$TEST_COMMIT_MSG"
echo "----------------------------------------"
echo ""

# ==================================================
# Step 5: 檢查必要的腳本文件
# ==================================================
echo "📋 Step 5: 檢查必要的腳本文件..."

REQUIRED_SCRIPTS=(
    "scripts/track-updates.js"
    "scripts/generate-metadata.js"
)

for script in "${REQUIRED_SCRIPTS[@]}"; do
    if [ -f "$script" ]; then
        echo "✅ $script 存在"
    else
        echo "⚠️  $script 不存在（可能需要創建）"
    fi
done
echo ""

# ==================================================
# Step 6: 測試運行 track-updates.js（如果存在）
# ==================================================
if [ -f "scripts/track-updates.js" ]; then
    echo "📋 Step 6: 測試運行 track-updates.js..."

    if node scripts/track-updates.js; then
        echo "✅ track-updates.js 執行成功"
    else
        echo "❌ track-updates.js 執行失敗"
    fi
    echo ""
else
    echo "⏭️  Step 6: 跳過（track-updates.js 不存在）"
    echo ""
fi

# ==================================================
# Step 7: 測試運行 generate-metadata.js（如果存在）
# ==================================================
if [ -f "scripts/generate-metadata.js" ]; then
    echo "📋 Step 7: 測試運行 generate-metadata.js..."

    if node scripts/generate-metadata.js; then
        echo "✅ generate-metadata.js 執行成功"
    else
        echo "❌ generate-metadata.js 執行失敗"
    fi
    echo ""
else
    echo "⏭️  Step 7: 跳過（generate-metadata.js 不存在）"
    echo ""
fi

# ==================================================
# Step 8: 檢查元數據文件
# ==================================================
echo "📋 Step 8: 檢查元數據文件..."

if [ -f "src/data/metadata/templateMetadata.json" ]; then
    echo "✅ templateMetadata.json 存在"

    # 使用 jq 或 node 來驗證 JSON 格式
    if command -v jq &> /dev/null; then
        if jq empty src/data/metadata/templateMetadata.json 2>/dev/null; then
            echo "✅ JSON 格式正確"

            # 顯示統計信息
            TOTAL=$(jq -r '.totalTemplates // 0' src/data/metadata/templateMetadata.json)
            echo "   總模板數: $TOTAL"
        else
            echo "❌ JSON 格式錯誤"
        fi
    else
        # 使用 node 驗證
        if node -e "JSON.parse(require('fs').readFileSync('src/data/metadata/templateMetadata.json', 'utf8'))" 2>/dev/null; then
            echo "✅ JSON 格式正確"
        else
            echo "❌ JSON 格式錯誤"
        fi
    fi
else
    echo "⚠️  templateMetadata.json 不存在"
fi
echo ""

# ==================================================
# 總結
# ==================================================
echo "=========================================="
echo "✅ 本地測試完成！"
echo "=========================================="
echo ""
echo "📝 測試摘要："
echo "  • YAML 語法：已在修復前驗證"
echo "  • Heredoc 語法：✅ 測試通過"
echo "  • 環境檢查：✅ 通過"
echo "  • Git repository：✅ 通過"
echo ""
echo "💡 下一步："
echo "  1. 如果所有測試通過，可以安全地提交修復"
echo "  2. 推送到 GitHub 後，觀察 Actions 執行結果"
echo "  3. 可選：安裝 'act' 工具進行更完整的本地測試"
echo ""
